// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VNFootballLeagues.Repositories.Models;

#nullable disable

namespace VNFootballLeagues.Repositories.Migrations
{
    [DbContext(typeof(VNFootballLeaguesDBContext))]
    partial class VNFootballLeaguesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("MessageId")
                        .HasName("PK__Message__C87C0C9CF30E6389");

                    b.HasIndex(new[] { "SessionId" }, "IX_Message_SessionId");

                    b.HasIndex(new[] { "Timestamp" }, "IX_Message_Timestamp");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.ChatSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionId")
                        .HasName("PK__ChatSess__C9F49290CFDB9472");

                    b.HasIndex(new[] { "StartTime" }, "IX_ChatSession_StartTime");

                    b.HasIndex(new[] { "UserId" }, "IX_ChatSession_UserId");

                    b.ToTable("ChatSession", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<double?>("Budget")
                        .HasColumnType("float");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClubId")
                        .HasName("PK__Club__D35058E7F99CA873");

                    b.ToTable("Club", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<string>("ContractType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("ContractId")
                        .HasName("PK__Contract__C90D3469F6B14076");

                    b.HasIndex(new[] { "IsActive" }, "IX_Contract_IsActive");

                    b.HasIndex(new[] { "PlayerId" }, "IX_Contract_PlayerId");

                    b.HasIndex(new[] { "TeamId" }, "IX_Contract_TeamId");

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.EmailVerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__EmailVer__3214EC075394A7A3");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Token" }, "IX_EmailVerificationToken_Token")
                        .IsUnique();

                    b.ToTable("EmailVerificationToken", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeagueId"));

                    b.Property<int?>("ApiLeagueId")
                        .HasColumnType("int");

                    b.Property<string>("LeagueName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LeagueType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("LeagueId")
                        .HasName("PK__League__10ABBCF494122950");

                    b.HasIndex(new[] { "ApiLeagueId" }, "UQ__League__A17F5C309759146E")
                        .IsUnique()
                        .HasFilter("[ApiLeagueId] IS NOT NULL");

                    b.ToTable("League", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Lineup", b =>
                {
                    b.Property<int>("LineupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineupId"));

                    b.Property<string>("Formation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("PlayersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("LineupId")
                        .HasName("PK__Lineups__492BA7DC1C443478");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("Lineups");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<int?>("ApiFixtureId")
                        .HasColumnType("int");

                    b.Property<int?>("ApiTimestamp")
                        .HasColumnType("int");

                    b.Property<int?>("ApiVenueId")
                        .HasColumnType("int");

                    b.Property<int?>("Attendance")
                        .HasColumnType("int");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("KickOffTime")
                        .HasColumnType("time");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PeriodFirstHalf")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodSecondHalf")
                        .HasColumnType("int");

                    b.Property<string>("RefereeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Round")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Venue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MatchId")
                        .HasName("PK__Match__4218C817300AB514");

                    b.HasIndex(new[] { "AwayTeamId" }, "IX_Match_AwayTeamId");

                    b.HasIndex(new[] { "HomeTeamId" }, "IX_Match_HomeTeamId");

                    b.HasIndex(new[] { "LeagueId" }, "IX_Match_LeagueId");

                    b.HasIndex(new[] { "MatchDate" }, "IX_Match_MatchDate");

                    b.HasIndex(new[] { "SeasonId" }, "IX_Match_SeasonId");

                    b.HasIndex(new[] { "ApiFixtureId" }, "UQ__Match__B0C36CDA95B10723")
                        .IsUnique()
                        .HasFilter("[ApiFixtureId] IS NOT NULL");

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.MatchEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int?>("ApiEventId")
                        .HasColumnType("int");

                    b.Property<int?>("AssistPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Detail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("EventTime")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ExtraTime")
                        .HasColumnType("int");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Period")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("EventId")
                        .HasName("PK__MatchEve__7944C810C6F9983F");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.MatchStatistic", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatId"));

                    b.Property<int?>("Clearances")
                        .HasColumnType("int");

                    b.Property<int?>("Corners")
                        .HasColumnType("int");

                    b.Property<int?>("DribblesAttempted")
                        .HasColumnType("int");

                    b.Property<int?>("DribblesSuccess")
                        .HasColumnType("int");

                    b.Property<int?>("DuelsTotal")
                        .HasColumnType("int");

                    b.Property<int?>("DuelsWon")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExpectedGoals")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("Fouls")
                        .HasColumnType("int");

                    b.Property<int?>("Interceptions")
                        .HasColumnType("int");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<int?>("Offsides")
                        .HasColumnType("int");

                    b.Property<int?>("PassesAccuracy")
                        .HasColumnType("int");

                    b.Property<int?>("PassesKey")
                        .HasColumnType("int");

                    b.Property<int?>("Possession")
                        .HasColumnType("int");

                    b.Property<int?>("RedCards")
                        .HasColumnType("int");

                    b.Property<int?>("Saves")
                        .HasColumnType("int");

                    b.Property<int?>("Shots")
                        .HasColumnType("int");

                    b.Property<int?>("ShotsBlocked")
                        .HasColumnType("int");

                    b.Property<int?>("ShotsInsideBox")
                        .HasColumnType("int");

                    b.Property<int?>("ShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("ShotsOutsideBox")
                        .HasColumnType("int");

                    b.Property<int?>("TacklesWon")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("StatId")
                        .HasName("PK__MatchSta__3A162D3E7BD005FF");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchStatistics");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Password__3214EC07EEFC636F");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Token" }, "IX_PasswordResetToken_Token")
                        .IsUnique();

                    b.ToTable("PasswordResetToken", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("ApiPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("BirthCountry")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool?>("IsInjured")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("PlayerId")
                        .HasName("PK__Player__4A4E74C8B01198BC");

                    b.HasIndex(new[] { "Nationality" }, "IX_Player_Nationality");

                    b.HasIndex(new[] { "TeamId" }, "IX_Player_TeamId");

                    b.HasIndex(new[] { "ApiPlayerId" }, "UQ__Player__40FC95B48F6B9EFC")
                        .IsUnique()
                        .HasFilter("[ApiPlayerId] IS NOT NULL");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.PlayerMatchStatistic", b =>
                {
                    b.Property<int>("PlayerMatchStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerMatchStatId"));

                    b.Property<int?>("AccurateCrosses")
                        .HasColumnType("int");

                    b.Property<int?>("AccurateLongBalls")
                        .HasColumnType("int");

                    b.Property<int?>("AccuratePassesOppositionHalf")
                        .HasColumnType("int");

                    b.Property<int?>("AccuratePassesOwnHalf")
                        .HasColumnType("int");

                    b.Property<int?>("AerialDuelsLost")
                        .HasColumnType("int");

                    b.Property<int?>("AerialDuelsWon")
                        .HasColumnType("int");

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("BallRecoveries")
                        .HasColumnType("int");

                    b.Property<int?>("Blocks")
                        .HasColumnType("int");

                    b.Property<int?>("Clearances")
                        .HasColumnType("int");

                    b.Property<int?>("Dispossessed")
                        .HasColumnType("int");

                    b.Property<int?>("DribblesAttempted")
                        .HasColumnType("int");

                    b.Property<int?>("DribblesSuccess")
                        .HasColumnType("int");

                    b.Property<int?>("DuelsTotal")
                        .HasColumnType("int");

                    b.Property<int?>("DuelsWon")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExpectedAssists")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExpectedGoals")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("FoulsCommitted")
                        .HasColumnType("int");

                    b.Property<int?>("FoulsDrawn")
                        .HasColumnType("int");

                    b.Property<int?>("Goals")
                        .HasColumnType("int");

                    b.Property<int?>("GroundDuelsLost")
                        .HasColumnType("int");

                    b.Property<int?>("GroundDuelsWon")
                        .HasColumnType("int");

                    b.Property<int?>("Interceptions")
                        .HasColumnType("int");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<int?>("Minutes")
                        .HasColumnType("int");

                    b.Property<int?>("Offsides")
                        .HasColumnType("int");

                    b.Property<int?>("Passes")
                        .HasColumnType("int");

                    b.Property<int?>("PassesAccuracy")
                        .HasColumnType("int");

                    b.Property<int?>("PassesKey")
                        .HasColumnType("int");

                    b.Property<int?>("PassesOppositionHalf")
                        .HasColumnType("int");

                    b.Property<int?>("PassesOwnHalf")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltiesCommitted")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltiesMissed")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltiesScored")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltiesWon")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PossessionLost")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int?>("RedCards")
                        .HasColumnType("int");

                    b.Property<int?>("Shots")
                        .HasColumnType("int");

                    b.Property<int?>("ShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("Tackles")
                        .HasColumnType("int");

                    b.Property<int?>("TacklesWon")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalCrosses")
                        .HasColumnType("int");

                    b.Property<int?>("TotalLongBalls")
                        .HasColumnType("int");

                    b.Property<int?>("Touches")
                        .HasColumnType("int");

                    b.Property<int?>("UnsuccessfulTouch")
                        .HasColumnType("int");

                    b.Property<int?>("WasFouled")
                        .HasColumnType("int");

                    b.Property<int?>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("PlayerMatchStatId")
                        .HasName("PK__PlayerMa__7941EF4E6BB07C63");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex(new[] { "MatchId" }, "IX_PlayerMatchStatistics_MatchId");

                    b.ToTable("PlayerMatchStatistics");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.PlayerSeasonStatistic", b =>
                {
                    b.Property<int>("PlayerStatisticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerStatisticsId"));

                    b.Property<int?>("Appearances")
                        .HasColumnType("int");

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("DribblesAttempted")
                        .HasColumnType("int");

                    b.Property<int?>("DribblesSuccess")
                        .HasColumnType("int");

                    b.Property<decimal?>("DribblesSuccessRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("DuelsTotal")
                        .HasColumnType("int");

                    b.Property<int?>("DuelsWon")
                        .HasColumnType("int");

                    b.Property<decimal?>("DuelsWonRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("FoulsCommitted")
                        .HasColumnType("int");

                    b.Property<int?>("FoulsDrawn")
                        .HasColumnType("int");

                    b.Property<int?>("Goals")
                        .HasColumnType("int");

                    b.Property<int?>("Interceptions")
                        .HasColumnType("int");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int?>("Lineups")
                        .HasColumnType("int");

                    b.Property<int?>("Minutes")
                        .HasColumnType("int");

                    b.Property<decimal?>("PassesAccuracy")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("PassesKey")
                        .HasColumnType("int");

                    b.Property<int?>("PassesTotal")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltiesMissed")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltiesScored")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int?>("RedCards")
                        .HasColumnType("int");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int?>("ShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("ShotsTotal")
                        .HasColumnType("int");

                    b.Property<int?>("SubstitutionsIn")
                        .HasColumnType("int");

                    b.Property<int?>("SubstitutionsOut")
                        .HasColumnType("int");

                    b.Property<int?>("Tackles")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("PlayerStatisticsId")
                        .HasName("PK__PlayerSe__D4A80B8924468805");

                    b.HasIndex("LeagueId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.HasIndex(new[] { "PlayerId" }, "IX_PlayerSeasonStatistics_PlayerId");

                    b.ToTable("PlayerSeasonStatistics");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC074AE78FFF");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Token" }, "IX_RefreshToken_Token")
                        .IsUnique();

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1A6BB4E1CE");

                    b.HasIndex(new[] { "RoleName" }, "IX_Role_RoleName")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.SePayWebhookLog", b =>
                {
                    b.Property<Guid>("WebhookLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingMessage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("SePayTransactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransferAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("WebhookLogId");

                    b.HasIndex(new[] { "ProcessingStatus" }, "IX_SePayWebhookLog_ProcessingStatus");

                    b.HasIndex(new[] { "ReceivedAt" }, "IX_SePayWebhookLog_ReceivedAt");

                    b.HasIndex(new[] { "SePayTransactionId" }, "IX_SePayWebhookLog_SePayTransactionId")
                        .IsUnique();

                    b.ToTable("SePayWebhookLog", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"));

                    b.Property<int?>("ApiSeasonId")
                        .HasColumnType("int");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("SeasonId")
                        .HasName("PK__Season__C1814E389AB36112");

                    b.HasIndex(new[] { "LeagueId" }, "IX_Season_LeagueId");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Sidelined", b =>
                {
                    b.Property<int>("SidelinedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SidelinedId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("GamesMissed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("SidelinedType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("SidelinedId")
                        .HasName("PK__Sideline__0960E42DC0CFF9A6");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.ToTable("Sidelined", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Stadium", b =>
                {
                    b.Property<int>("StadiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StadiumId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ApiVenueId")
                        .HasColumnType("int");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("IsNationalStadium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("StadiumName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Surface")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StadiumId")
                        .HasName("PK__Stadium__ED8330583874B553");

                    b.HasIndex(new[] { "ApiVenueId" }, "UQ__Stadium__6F33BECC523957D7")
                        .IsUnique()
                        .HasFilter("[ApiVenueId] IS NOT NULL");

                    b.ToTable("Stadium", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Standing", b =>
                {
                    b.Property<int>("StandingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StandingId"));

                    b.Property<DateTime?>("ApiLastUpdated")
                        .HasColumnType("datetime");

                    b.Property<string>("AwayRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Draw")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GoalDifference")
                        .HasColumnType("int");

                    b.Property<int?>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int?>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<string>("HomeRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int?>("Loss")
                        .HasColumnType("int");

                    b.Property<int?>("Played")
                        .HasColumnType("int");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("Win")
                        .HasColumnType("int");

                    b.HasKey("StandingId")
                        .HasName("PK__Standing__FC2758C18EA6C935");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.HasIndex(new[] { "LeagueId", "SeasonId" }, "IX_Standings_LeagueId_SeasonId");

                    b.ToTable("Standings");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.SubscriptionPayment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gateway")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("QrUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SePayReferenceCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("SePayTransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SePayTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TransferContent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentId");

                    b.HasIndex(new[] { "ExpiresAt" }, "IX_SubscriptionPayment_ExpiresAt");

                    b.HasIndex(new[] { "PaymentCode" }, "IX_SubscriptionPayment_PaymentCode")
                        .IsUnique();

                    b.HasIndex(new[] { "Status" }, "IX_SubscriptionPayment_Status");

                    b.HasIndex(new[] { "UserId" }, "IX_SubscriptionPayment_UserId");

                    b.ToTable("SubscriptionPayment", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int?>("ApiTeamId")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int?>("Founded")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("National")
                        .HasColumnType("bit");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeamId")
                        .HasName("PK__Team__123AE799A9C8BB32");

                    b.HasIndex("ClubId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.TeamStatistic", b =>
                {
                    b.Property<int>("TeamStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamStatId"));

                    b.Property<int?>("AwayDraws")
                        .HasColumnType("int");

                    b.Property<int?>("AwayGoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int?>("AwayGoalsFor")
                        .HasColumnType("int");

                    b.Property<int?>("AwayLosses")
                        .HasColumnType("int");

                    b.Property<int?>("AwayPlayed")
                        .HasColumnType("int");

                    b.Property<int?>("AwayWins")
                        .HasColumnType("int");

                    b.Property<int?>("BiggestGoalsAgainstAway")
                        .HasColumnType("int");

                    b.Property<int?>("BiggestGoalsAgainstHome")
                        .HasColumnType("int");

                    b.Property<int?>("BiggestGoalsForAway")
                        .HasColumnType("int");

                    b.Property<int?>("BiggestGoalsForHome")
                        .HasColumnType("int");

                    b.Property<string>("BiggestLossAway")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BiggestLossHome")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("BiggestStreakDraws")
                        .HasColumnType("int");

                    b.Property<int?>("BiggestStreakLosses")
                        .HasColumnType("int");

                    b.Property<int?>("BiggestStreakWins")
                        .HasColumnType("int");

                    b.Property<string>("BiggestWinAway")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BiggestWinHome")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CleanSheets")
                        .HasColumnType("int");

                    b.Property<int?>("CleanSheetsAway")
                        .HasColumnType("int");

                    b.Property<int?>("CleanSheetsHome")
                        .HasColumnType("int");

                    b.Property<int?>("Draws")
                        .HasColumnType("int");

                    b.Property<int?>("FailedToScore")
                        .HasColumnType("int");

                    b.Property<int?>("FailedToScoreAway")
                        .HasColumnType("int");

                    b.Property<int?>("FailedToScoreHome")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<string>("GoalsAgainstAvgAway")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GoalsAgainstAvgHome")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GoalsAgainstAvgTotal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GoalsAgainstMinute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<string>("GoalsForAvgAway")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GoalsForAvgHome")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GoalsForAvgTotal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GoalsForMinute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HomeDraws")
                        .HasColumnType("int");

                    b.Property<int?>("HomeGoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int?>("HomeGoalsFor")
                        .HasColumnType("int");

                    b.Property<int?>("HomeLosses")
                        .HasColumnType("int");

                    b.Property<int?>("HomePlayed")
                        .HasColumnType("int");

                    b.Property<int?>("HomeWins")
                        .HasColumnType("int");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int?>("Losses")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltiesMissed")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltiesScored")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltiesTotal")
                        .HasColumnType("int");

                    b.Property<string>("PenaltyPercentage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Played")
                        .HasColumnType("int");

                    b.Property<string>("RedCardsMinute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("UnderOverAgainst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnderOverFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wins")
                        .HasColumnType("int");

                    b.Property<string>("YellowCardsMinute")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamStatId")
                        .HasName("PK__TeamStat__A0F24F8C8E4B5481");

                    b.HasIndex("LeagueId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamStatistics");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Transfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferId"));

                    b.Property<int?>("FromTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("ToTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransferDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TransferType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransferId")
                        .HasName("PK__Transfer__954900915944B500");

                    b.HasIndex("FromTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ToTeamId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C6323F744");

                    b.HasIndex(new[] { "Email" }, "IX_User_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "IX_User_Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.UserSubscription", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPaymentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "ExpiresAt" }, "IX_UserSubscription_ExpiresAt");

                    b.HasIndex(new[] { "Status" }, "IX_UserSubscription_Status");

                    b.ToTable("UserSubscription", (string)null);
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.ChatMessage", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Message_ChatSession");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.ChatSession", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChatSession_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Contract", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.Player", "Player")
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK__Contract__Player__06CD04F7");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "Team")
                        .WithMany("Contracts")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("FK__Contract__TeamId__07C12930");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.EmailVerificationToken", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmailVerificationToken_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Lineup", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.Match", "Match")
                        .WithMany("Lineups")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("FK__Lineups__MatchId__29221CFB");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "Team")
                        .WithMany("Lineups")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__Lineups__TeamId__2A164134");

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Match", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "AwayTeam")
                        .WithMany("MatchAwayTeams")
                        .HasForeignKey("AwayTeamId")
                        .HasConstraintName("FK__Match__AwayTeamI__0E6E26BF");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "HomeTeam")
                        .WithMany("MatchHomeTeams")
                        .HasForeignKey("HomeTeamId")
                        .HasConstraintName("FK__Match__HomeTeamI__0D7A0286");

                    b.HasOne("VNFootballLeagues.Repositories.Models.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .HasConstraintName("FK__Match__LeagueId__0B91BA14");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("FK__Match__SeasonId__0C85DE4D");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.MatchEvent", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.Match", "Match")
                        .WithMany("MatchEvents")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("FK__MatchEven__Match__245D67DE");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Player", "Player")
                        .WithMany("MatchEvents")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK__MatchEven__Playe__2645B050");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "Team")
                        .WithMany("MatchEvents")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__MatchEven__TeamI__25518C17");

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.MatchStatistic", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.Match", "Match")
                        .WithMany("MatchStatistics")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("FK__MatchStat__Match__208CD6FA");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "Team")
                        .WithMany("MatchStatistics")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__MatchStat__TeamI__2180FB33");

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.PasswordResetToken", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PasswordResetToken_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Player", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__Player__TeamId__02FC7413");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.PlayerMatchStatistic", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.Match", "Match")
                        .WithMany("PlayerMatchStatistics")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("FK__PlayerMat__Match__2CF2ADDF");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Player", "Player")
                        .WithMany("PlayerMatchStatistics")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK__PlayerMat__Playe__2DE6D218");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "Team")
                        .WithMany("PlayerMatchStatistics")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__PlayerMat__TeamI__2EDAF651");

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.PlayerSeasonStatistic", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.League", "League")
                        .WithMany("PlayerSeasonStatistics")
                        .HasForeignKey("LeagueId")
                        .HasConstraintName("FK__PlayerSea__Leagu__1CBC4616");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Player", "Player")
                        .WithMany("PlayerSeasonStatistics")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK__PlayerSea__Playe__1AD3FDA4");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Season", "Season")
                        .WithMany("PlayerSeasonStatistics")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("FK__PlayerSea__Seaso__1DB06A4F");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "Team")
                        .WithMany("PlayerSeasonStatistics")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__PlayerSea__TeamI__1BC821DD");

                    b.Navigation("League");

                    b.Navigation("Player");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.RefreshToken", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Season", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .HasConstraintName("FK__Season__LeagueId__73BA3083");

                    b.Navigation("League");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Sidelined", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.Player", "Player")
                        .WithMany("Sidelineds")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK__Sidelined__Playe__3864608B");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Season", "Season")
                        .WithMany("Sidelineds")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("FK__Sidelined__Seaso__3A4CA8FD");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "Team")
                        .WithMany("Sidelineds")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__Sidelined__TeamI__395884C4");

                    b.Navigation("Player");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Standing", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.League", "League")
                        .WithMany("Standings")
                        .HasForeignKey("LeagueId")
                        .HasConstraintName("FK__Standings__Leagu__114A936A");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Season", "Season")
                        .WithMany("Standings")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("FK__Standings__Seaso__123EB7A3");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "Team")
                        .WithMany("Standings")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__Standings__TeamI__1332DBDC");

                    b.Navigation("League");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.SubscriptionPayment", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubscriptionPayment_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Team", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.Club", "Club")
                        .WithMany("Teams")
                        .HasForeignKey("ClubId")
                        .IsRequired()
                        .HasConstraintName("FK_Team_Club");

                    b.HasOne("VNFootballLeagues.Repositories.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .IsRequired()
                        .HasConstraintName("FK_Team_League");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Stadium", "Stadium")
                        .WithMany("Teams")
                        .HasForeignKey("StadiumId")
                        .HasConstraintName("FK_Team_Stadium");

                    b.Navigation("Club");

                    b.Navigation("League");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.TeamStatistic", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.League", "League")
                        .WithMany("TeamStatistics")
                        .HasForeignKey("LeagueId")
                        .HasConstraintName("FK__TeamStati__Leagu__32AB8735");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Season", "Season")
                        .WithMany("TeamStatistics")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("FK__TeamStati__Seaso__339FAB6E");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "Team")
                        .WithMany("TeamStatistics")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__TeamStati__TeamI__31B762FC");

                    b.Navigation("League");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Transfer", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "FromTeam")
                        .WithMany("TransferFromTeams")
                        .HasForeignKey("FromTeamId")
                        .HasConstraintName("FK__Transfers__FromT__17036CC0");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Player", "Player")
                        .WithMany("Transfers")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK__Transfers__Playe__160F4887");

                    b.HasOne("VNFootballLeagues.Repositories.Models.Team", "ToTeam")
                        .WithMany("TransferToTeams")
                        .HasForeignKey("ToTeamId")
                        .HasConstraintName("FK__Transfers__ToTea__17F790F9");

                    b.Navigation("FromTeam");

                    b.Navigation("Player");

                    b.Navigation("ToTeam");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.UserRole", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Role");

                    b.HasOne("VNFootballLeagues.Repositories.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_User");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.UserSubscription", b =>
                {
                    b.HasOne("VNFootballLeagues.Repositories.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSubscription_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Club", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.League", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("PlayerSeasonStatistics");

                    b.Navigation("Seasons");

                    b.Navigation("Standings");

                    b.Navigation("TeamStatistics");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Match", b =>
                {
                    b.Navigation("Lineups");

                    b.Navigation("MatchEvents");

                    b.Navigation("MatchStatistics");

                    b.Navigation("PlayerMatchStatistics");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Player", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("MatchEvents");

                    b.Navigation("PlayerMatchStatistics");

                    b.Navigation("PlayerSeasonStatistics");

                    b.Navigation("Sidelineds");

                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Season", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("PlayerSeasonStatistics");

                    b.Navigation("Sidelineds");

                    b.Navigation("Standings");

                    b.Navigation("TeamStatistics");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Stadium", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.Team", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Lineups");

                    b.Navigation("MatchAwayTeams");

                    b.Navigation("MatchEvents");

                    b.Navigation("MatchHomeTeams");

                    b.Navigation("MatchStatistics");

                    b.Navigation("PlayerMatchStatistics");

                    b.Navigation("PlayerSeasonStatistics");

                    b.Navigation("Players");

                    b.Navigation("Sidelineds");

                    b.Navigation("Standings");

                    b.Navigation("TeamStatistics");

                    b.Navigation("TransferFromTeams");

                    b.Navigation("TransferToTeams");
                });

            modelBuilder.Entity("VNFootballLeagues.Repositories.Models.User", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
