// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class VNFootballLeaguesDBContext : DbContext
{
    public VNFootballLeaguesDBContext()
    {
    }

    public VNFootballLeaguesDBContext(DbContextOptions<VNFootballLeaguesDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ChatSession> ChatSessions { get; set; }

    public virtual DbSet<Club> Clubs { get; set; }

    public virtual DbSet<CupTree> CupTrees { get; set; }

    public virtual DbSet<Contract> Contracts { get; set; }

    public virtual DbSet<EmailVerificationToken> EmailVerificationTokens { get; set; }

    public virtual DbSet<League> Leagues { get; set; }

    public virtual DbSet<Lineup> Lineups { get; set; }

    public virtual DbSet<Match> Matches { get; set; }

    public virtual DbSet<MatchEvent> MatchEvents { get; set; }

    public virtual DbSet<MatchStatistic> MatchStatistics { get; set; }

    public virtual DbSet<ChatMessage> ChatMessages { get; set; }

    public virtual DbSet<PasswordResetToken> PasswordResetTokens { get; set; }

    public virtual DbSet<Player> Players { get; set; }

    public virtual DbSet<PlayerMatchStatistic> PlayerMatchStatistics { get; set; }

    public virtual DbSet<PlayerSeasonStatistic> PlayerSeasonStatistics { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Season> Seasons { get; set; }

    public virtual DbSet<Sidelined> Sidelineds { get; set; }

    public virtual DbSet<Stadium> Stadiums { get; set; }

    public virtual DbSet<Standing> Standings { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamStatistic> TeamStatistics { get; set; }

    public virtual DbSet<Transfer> Transfers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
       => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).EnableSensitiveDataLogging()
       .LogTo(Console.WriteLine, LogLevel.Information);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChatSession>(entity =>
        {
            entity.HasKey(e => e.SessionId).HasName("PK__ChatSess__C9F49290CFDB9472");

            entity.ToTable("ChatSession");

            entity.HasIndex(e => e.StartTime, "IX_ChatSession_StartTime");

            entity.HasIndex(e => e.UserId, "IX_ChatSession_UserId");

            entity.Property(e => e.SessionId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.StartTime).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Title).HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.ChatSessions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_ChatSession_User");
        });

        modelBuilder.Entity<Club>(entity =>
        {
            entity.HasKey(e => e.ClubId).HasName("PK__Club__D35058E7F99CA873");

            entity.ToTable("Club");

            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.ClubName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Owner).HasMaxLength(50);
        });

        modelBuilder.Entity<Contract>(entity =>
        {
            entity.HasKey(e => e.ContractId).HasName("PK__Contract__C90D3469F6B14076");

            entity.ToTable("Contract");

            entity.HasIndex(e => e.IsActive, "IX_Contract_IsActive");

            entity.HasIndex(e => e.PlayerId, "IX_Contract_PlayerId");

            entity.HasIndex(e => e.TeamId, "IX_Contract_TeamId");

            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Player).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contract__Player__06CD04F7");

            entity.HasOne(d => d.Team).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contract__TeamId__07C12930");
        });

        modelBuilder.Entity<EmailVerificationToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EmailVer__3214EC075394A7A3");

            entity.ToTable("EmailVerificationToken");

            entity.HasIndex(e => e.Token, "IX_EmailVerificationToken_Token").IsUnique();

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.User).WithMany(p => p.EmailVerificationTokens)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_EmailVerificationToken_User");
        });

        modelBuilder.Entity<League>(entity =>
        {
            entity.HasKey(e => e.LeagueId).HasName("PK__League__10ABBCF494122950");

            entity.ToTable("League");

            entity.HasIndex(e => e.ApiLeagueId, "UQ__League__A17F5C309759146E").IsUnique();

            entity.Property(e => e.LeagueName).HasMaxLength(200);
            entity.Property(e => e.LeagueType).HasMaxLength(50);
            entity.Property(e => e.LogoUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Lineup>(entity =>
        {
            entity.HasKey(e => e.LineupId).HasName("PK__Lineups__492BA7DC1C443478");

            entity.Property(e => e.Formation).HasMaxLength(50);

            entity.HasOne(d => d.Match).WithMany(p => p.Lineups)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK__Lineups__MatchId__29221CFB");

            entity.HasOne(d => d.Team).WithMany(p => p.Lineups)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__Lineups__TeamId__2A164134");
        });

        modelBuilder.Entity<Match>(entity =>
        {
            entity.HasKey(e => e.MatchId).HasName("PK__Match__4218C817300AB514");

            entity.ToTable("Match");

            entity.HasIndex(e => e.AwayTeamId, "IX_Match_AwayTeamId");

            entity.HasIndex(e => e.HomeTeamId, "IX_Match_HomeTeamId");

            entity.HasIndex(e => e.LeagueId, "IX_Match_LeagueId");

            entity.HasIndex(e => e.MatchDate, "IX_Match_MatchDate");

            entity.HasIndex(e => e.SeasonId, "IX_Match_SeasonId");

            entity.HasIndex(e => e.ApiFixtureId, "UQ__Match__B0C36CDA95B10723").IsUnique();

            entity.Property(e => e.MatchDate).HasColumnType("datetime");
            entity.Property(e => e.RefereeName).HasMaxLength(200);
            entity.Property(e => e.Round).HasMaxLength(50);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.Timezone).HasMaxLength(50);
            entity.Property(e => e.Venue).HasMaxLength(255);

            entity.HasOne(d => d.AwayTeam).WithMany(p => p.MatchAwayTeams)
                .HasForeignKey(d => d.AwayTeamId)
                .HasConstraintName("FK__Match__AwayTeamI__0E6E26BF");

            entity.HasOne(d => d.HomeTeam).WithMany(p => p.MatchHomeTeams)
                .HasForeignKey(d => d.HomeTeamId)
                .HasConstraintName("FK__Match__HomeTeamI__0D7A0286");

            entity.HasOne(d => d.League).WithMany(p => p.Matches)
                .HasForeignKey(d => d.LeagueId)
                .HasConstraintName("FK__Match__LeagueId__0B91BA14");

            entity.HasOne(d => d.Season).WithMany(p => p.Matches)
                .HasForeignKey(d => d.SeasonId)
                .HasConstraintName("FK__Match__SeasonId__0C85DE4D");
        });

        modelBuilder.Entity<MatchEvent>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK__MatchEve__7944C810C6F9983F");

            entity.Property(e => e.Comments).HasMaxLength(255);
            entity.Property(e => e.Detail).HasMaxLength(50);
            entity.Property(e => e.EventType).HasMaxLength(50);
            entity.Property(e => e.Period).HasMaxLength(20);

            entity.HasOne(d => d.Match).WithMany(p => p.MatchEvents)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK__MatchEven__Match__245D67DE");

            entity.HasOne(d => d.Player).WithMany(p => p.MatchEvents)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK__MatchEven__Playe__2645B050");

            entity.HasOne(d => d.Team).WithMany(p => p.MatchEvents)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__MatchEven__TeamI__25518C17");
        });

        modelBuilder.Entity<MatchStatistic>(entity =>
        {
            entity.HasKey(e => e.StatId).HasName("PK__MatchSta__3A162D3E7BD005FF");

            entity.Property(e => e.ExpectedGoals).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Match).WithMany(p => p.MatchStatistics)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK__MatchStat__Match__208CD6FA");

            entity.HasOne(d => d.Team).WithMany(p => p.MatchStatistics)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__MatchStat__TeamI__2180FB33");
        });

        modelBuilder.Entity<ChatMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Message__C87C0C9CF30E6389");

            entity.ToTable("Message");

            entity.HasIndex(e => e.SessionId, "IX_Message_SessionId");

            entity.HasIndex(e => e.Timestamp, "IX_Message_Timestamp");

            entity.Property(e => e.MessageId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Sender)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Text).IsRequired();
            entity.Property(e => e.Timestamp).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.Session).WithMany(p => p.Messages)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("FK_Message_ChatSession");
        });

        modelBuilder.Entity<PasswordResetToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Password__3214EC07EEFC636F");

            entity.ToTable("PasswordResetToken");

            entity.HasIndex(e => e.Token, "IX_PasswordResetToken_Token").IsUnique();

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.User).WithMany(p => p.PasswordResetTokens)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_PasswordResetToken_User");
        });

        modelBuilder.Entity<Player>(entity =>
        {
            entity.HasKey(e => e.PlayerId).HasName("PK__Player__4A4E74C8B01198BC");

            entity.ToTable("Player");

            entity.HasIndex(e => e.Nationality, "IX_Player_Nationality");

            entity.HasIndex(e => e.TeamId, "IX_Player_TeamId");

            entity.HasIndex(e => e.ApiPlayerId, "UQ__Player__40FC95B48F6B9EFC").IsUnique();

            entity.Property(e => e.BirthCountry).HasMaxLength(200);
            entity.Property(e => e.BirthPlace).HasMaxLength(200);
            entity.Property(e => e.FirstName).HasMaxLength(200);
            entity.Property(e => e.FullName).HasMaxLength(200);
            entity.Property(e => e.HeightCm).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LastName).HasMaxLength(200);
            entity.Property(e => e.Nationality).HasMaxLength(100);
            entity.Property(e => e.PhotoUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Position).HasMaxLength(50);
            entity.Property(e => e.WeightKg).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Team).WithMany(p => p.Players)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__Player__TeamId__02FC7413");
        });

        modelBuilder.Entity<PlayerMatchStatistic>(entity =>
        {
            entity.HasKey(e => e.PlayerMatchStatId).HasName("PK__PlayerMa__7941EF4E6BB07C63");

            entity.HasIndex(e => e.MatchId, "IX_PlayerMatchStatistics_MatchId");

            entity.Property(e => e.ExpectedGoals).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Rating).HasColumnType("decimal(3, 2)");

            entity.HasOne(d => d.Match).WithMany(p => p.PlayerMatchStatistics)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK__PlayerMat__Match__2CF2ADDF");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerMatchStatistics)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK__PlayerMat__Playe__2DE6D218");

            entity.HasOne(d => d.Team).WithMany(p => p.PlayerMatchStatistics)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__PlayerMat__TeamI__2EDAF651");
        });

        modelBuilder.Entity<PlayerSeasonStatistic>(entity =>
        {
            entity.HasKey(e => e.PlayerStatisticsId).HasName("PK__PlayerSe__D4A80B8924468805");

            entity.HasIndex(e => e.PlayerId, "IX_PlayerSeasonStatistics_PlayerId");

            entity.Property(e => e.DribblesSuccessRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DuelsWonRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.PassesAccuracy).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Rating).HasColumnType("decimal(3, 2)");

            entity.HasOne(d => d.League).WithMany(p => p.PlayerSeasonStatistics)
                .HasForeignKey(d => d.LeagueId)
                .HasConstraintName("FK__PlayerSea__Leagu__1CBC4616");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerSeasonStatistics)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK__PlayerSea__Playe__1AD3FDA4");

            entity.HasOne(d => d.Season).WithMany(p => p.PlayerSeasonStatistics)
                .HasForeignKey(d => d.SeasonId)
                .HasConstraintName("FK__PlayerSea__Seaso__1DB06A4F");

            entity.HasOne(d => d.Team).WithMany(p => p.PlayerSeasonStatistics)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__PlayerSea__TeamI__1BC821DD");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RefreshT__3214EC074AE78FFF");

            entity.ToTable("RefreshToken");

            entity.HasIndex(e => e.Token, "IX_RefreshToken_Token").IsUnique();

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_RefreshToken_User");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE1A6BB4E1CE");

            entity.ToTable("Role");

            entity.HasIndex(e => e.RoleName, "IX_Role_RoleName").IsUnique();

            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Season>(entity =>
        {
            entity.HasKey(e => e.SeasonId).HasName("PK__Season__C1814E389AB36112");

            entity.ToTable("Season");

            entity.HasIndex(e => e.LeagueId, "IX_Season_LeagueId");

            entity.HasOne(d => d.League).WithMany(p => p.Seasons)
                .HasForeignKey(d => d.LeagueId)
                .HasConstraintName("FK__Season__LeagueId__73BA3083");
        });

        modelBuilder.Entity<Sidelined>(entity =>
        {
            entity.HasKey(e => e.SidelinedId).HasName("PK__Sideline__0960E42DC0CFF9A6");

            entity.ToTable("Sidelined");

            entity.Property(e => e.GamesMissed).HasDefaultValue(0);
            entity.Property(e => e.IsCompleted).HasDefaultValue(false);
            entity.Property(e => e.SidelinedType).HasMaxLength(50);

            entity.HasOne(d => d.Player).WithMany(p => p.Sidelineds)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK__Sidelined__Playe__3864608B");

            entity.HasOne(d => d.Season).WithMany(p => p.Sidelineds)
                .HasForeignKey(d => d.SeasonId)
                .HasConstraintName("FK__Sidelined__Seaso__3A4CA8FD");

            entity.HasOne(d => d.Team).WithMany(p => p.Sidelineds)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__Sidelined__TeamI__395884C4");
        });

        modelBuilder.Entity<Stadium>(entity =>
        {
            entity.HasKey(e => e.StadiumId).HasName("PK__Stadium__ED8330583874B553");

            entity.ToTable("Stadium");

            entity.HasIndex(e => e.ApiVenueId, "UQ__Stadium__6F33BECC523957D7").IsUnique();

            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.City).HasMaxLength(200);
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.IsNationalStadium).HasDefaultValue(false);
            entity.Property(e => e.StadiumName).HasMaxLength(200);
            entity.Property(e => e.Surface).HasMaxLength(50);
        });

        modelBuilder.Entity<Standing>(entity =>
        {
            entity.HasKey(e => e.StandingId).HasName("PK__Standing__FC2758C18EA6C935");

            entity.HasIndex(e => new { e.LeagueId, e.SeasonId }, "IX_Standings_LeagueId_SeasonId");

            entity.Property(e => e.ApiLastUpdated).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Form).HasMaxLength(50);
            entity.Property(e => e.Status).HasMaxLength(20);

            entity.HasOne(d => d.League).WithMany(p => p.Standings)
                .HasForeignKey(d => d.LeagueId)
                .HasConstraintName("FK__Standings__Leagu__114A936A");

            entity.HasOne(d => d.Season).WithMany(p => p.Standings)
                .HasForeignKey(d => d.SeasonId)
                .HasConstraintName("FK__Standings__Seaso__123EB7A3");

            entity.HasOne(d => d.Team).WithMany(p => p.Standings)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__Standings__TeamI__1332DBDC");
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.TeamId).HasName("PK__Team__123AE799A9C8BB32");

            entity.ToTable("Team");

            entity.Property(e => e.LogoUrl).HasMaxLength(255);
            entity.Property(e => e.ShortName).HasMaxLength(20);
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Club).WithMany(p => p.Teams)
                .HasForeignKey(d => d.ClubId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Team_Club");

            entity.HasOne(d => d.League).WithMany(p => p.Teams)
                .HasForeignKey(d => d.LeagueId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Team_League");

            entity.HasOne(d => d.Stadium).WithMany(p => p.Teams)
                .HasForeignKey(d => d.StadiumId)
                .HasConstraintName("FK_Team_Stadium");
        });

        modelBuilder.Entity<TeamStatistic>(entity =>
        {
            entity.HasKey(e => e.TeamStatId).HasName("PK__TeamStat__A0F24F8C8E4B5481");

            entity.Property(e => e.BiggestLossAway).HasMaxLength(20);
            entity.Property(e => e.BiggestLossHome).HasMaxLength(20);
            entity.Property(e => e.BiggestWinAway).HasMaxLength(20);
            entity.Property(e => e.BiggestWinHome).HasMaxLength(20);
            entity.Property(e => e.Form).HasMaxLength(100);
            entity.Property(e => e.GoalsAgainstAvgAway).HasMaxLength(10);
            entity.Property(e => e.GoalsAgainstAvgHome).HasMaxLength(10);
            entity.Property(e => e.GoalsAgainstAvgTotal).HasMaxLength(10);
            entity.Property(e => e.GoalsForAvgAway).HasMaxLength(10);
            entity.Property(e => e.GoalsForAvgHome).HasMaxLength(10);
            entity.Property(e => e.GoalsForAvgTotal).HasMaxLength(10);
            entity.Property(e => e.PenaltyPercentage).HasMaxLength(10);

            entity.HasOne(d => d.League).WithMany(p => p.TeamStatistics)
                .HasForeignKey(d => d.LeagueId)
                .HasConstraintName("FK__TeamStati__Leagu__32AB8735");

            entity.HasOne(d => d.Season).WithMany(p => p.TeamStatistics)
                .HasForeignKey(d => d.SeasonId)
                .HasConstraintName("FK__TeamStati__Seaso__339FAB6E");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamStatistics)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__TeamStati__TeamI__31B762FC");
        });

        modelBuilder.Entity<Transfer>(entity =>
        {
            entity.HasKey(e => e.TransferId);

            entity.Property(e => e.ApiTransferId).IsRequired();

            entity.Property(e => e.FromTeam).HasMaxLength(200);
            entity.Property(e => e.ToTeam).HasMaxLength(200);

            entity.Property(e => e.TransferType).HasMaxLength(50);
            entity.Property(e => e.TransferFee).HasMaxLength(50);

            entity.HasOne(d => d.Player)
                .WithMany(p => p.Transfers)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CC4C6323F744");

            entity.ToTable("User");

            entity.HasIndex(e => e.Email, "IX_User_Email").IsUnique();

            entity.HasIndex(e => e.Username, "IX_User_Username").IsUnique();

            entity.Property(e => e.UserId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId });

            entity.ToTable("UserRole");

            entity.Property(e => e.AssignedAt).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_UserRole_Role");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserRole_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}