// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Azure.Documents;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;

namespace VNFootballLeagues.Repositories.Models;

public partial class VNFootballLeaguesDBContext : DbContext
{
    public VNFootballLeaguesDBContext()
    {
    }

    public VNFootballLeaguesDBContext(DbContextOptions<VNFootballLeaguesDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Club> Clubs { get; set; }

    public virtual DbSet<Contract> Contracts { get; set; }

    public virtual DbSet<League> Leagues { get; set; }

    public virtual DbSet<Lineup> Lineups { get; set; }

    public virtual DbSet<Match> Matches { get; set; }

    public virtual DbSet<MatchEvent> MatchEvents { get; set; }

    public virtual DbSet<MatchStatistic> MatchStatistics { get; set; }

    public virtual DbSet<Player> Players { get; set; }

    public virtual DbSet<PlayerMatchStatistic> PlayerMatchStatistics { get; set; }

    public virtual DbSet<PlayerSeasonStatistic> PlayerSeasonStatistics { get; set; }

    public virtual DbSet<Season> Seasons { get; set; }

    public virtual DbSet<Sidelined> Sidelineds { get; set; }

    public virtual DbSet<Stadium> Stadiums { get; set; }

    public virtual DbSet<Standing> Standings { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamStatistic> TeamStatistics { get; set; }

    public virtual DbSet<Transfer> Transfers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<EmailVerificationToken> EmailVerificationTokens { get; set; }

    public virtual DbSet<PasswordResetToken> PasswordResetTokens { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
       => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).EnableSensitiveDataLogging()
       .LogTo(Console.WriteLine, LogLevel.Information);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Club>(entity =>
        {
            entity.HasKey(e => e.ClubId).HasName("PK__Club__D35058E7E90D7AA7");

            entity.ToTable("Club");

            entity.Property(e => e.City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ClubName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Owner)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Contract>(entity =>
        {
            entity.HasKey(e => e.ContractId).HasName("PK__Contract__C90D34698185861F");

            entity.ToTable("Contract");

            entity.HasIndex(e => e.IsActive, "IX_Contract_IsActive");

            entity.HasIndex(e => e.PlayerId, "IX_Contract_PlayerId");

            entity.HasIndex(e => e.TeamId, "IX_Contract_TeamId");

            entity.Property(e => e.ContractType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Salary).HasColumnType("decimal(15, 2)");

            entity.HasOne(d => d.Player).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contract__Player__52593CB8");

            entity.HasOne(d => d.Team).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contract__TeamId__534D60F1");
        });

        modelBuilder.Entity<League>(entity =>
        {
            entity.HasKey(e => e.LeagueId).HasName("PK__League__10ABBCF4C3D66EE5");

            entity.ToTable("League");

            entity.HasIndex(e => e.ApiLeagueId, "UQ__League__A17F5C307955B98F").IsUnique();

            entity.Property(e => e.LeagueName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.LeagueType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LogoUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Lineup>(entity =>
        {
            entity.HasKey(e => e.LineupId).HasName("PK__Lineups__492BA7DCF20BEFF7");

            entity.Property(e => e.Formation)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Match).WithMany(p => p.Lineups)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK__Lineups__MatchId__74AE54BC");

            entity.HasOne(d => d.Team).WithMany(p => p.Lineups)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__Lineups__TeamId__75A278F5");
        });

        modelBuilder.Entity<Match>(entity =>
        {
            entity.HasKey(e => e.MatchId).HasName("PK__Match__4218C817D265B8CC");

            entity.ToTable("Match");

            entity.HasIndex(e => e.AwayTeamId, "IX_Match_AwayTeamId");

            entity.HasIndex(e => e.HomeTeamId, "IX_Match_HomeTeamId");

            entity.HasIndex(e => e.LeagueId, "IX_Match_LeagueId");

            entity.HasIndex(e => e.MatchDate, "IX_Match_MatchDate");

            entity.HasIndex(e => e.SeasonId, "IX_Match_SeasonId");

            entity.HasIndex(e => e.ApiFixtureId, "UQ__Match__B0C36CDAC377D50B").IsUnique();

            entity.Property(e => e.MatchDate).HasColumnType("datetime");
            entity.Property(e => e.RefereeName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Round)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Timezone)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Venue)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.AwayTeam).WithMany(p => p.MatchAwayTeams)
                .HasForeignKey(d => d.AwayTeamId)
                .HasConstraintName("FK__Match__AwayTeamI__59FA5E80");

            entity.HasOne(d => d.HomeTeam).WithMany(p => p.MatchHomeTeams)
                .HasForeignKey(d => d.HomeTeamId)
                .HasConstraintName("FK__Match__HomeTeamI__59063A47");

            entity.HasOne(d => d.League).WithMany(p => p.Matches)
                .HasForeignKey(d => d.LeagueId)
                .HasConstraintName("FK__Match__LeagueId__571DF1D5");

            entity.HasOne(d => d.Season).WithMany(p => p.Matches)
                .HasForeignKey(d => d.SeasonId)
                .HasConstraintName("FK__Match__SeasonId__5812160E");
        });

        modelBuilder.Entity<MatchEvent>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK__MatchEve__7944C810A591BA34");

            entity.Property(e => e.Comments)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Detail)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EventType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Period)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Match).WithMany(p => p.MatchEvents)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK__MatchEven__Match__6FE99F9F");

            entity.HasOne(d => d.Player).WithMany(p => p.MatchEvents)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK__MatchEven__Playe__71D1E811");

            entity.HasOne(d => d.Team).WithMany(p => p.MatchEvents)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__MatchEven__TeamI__70DDC3D8");
        });

        modelBuilder.Entity<MatchStatistic>(entity =>
        {
            entity.HasKey(e => e.StatId).HasName("PK__MatchSta__3A162D3EF689E3DA");

            entity.Property(e => e.ExpectedGoals).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Match).WithMany(p => p.MatchStatistics)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK__MatchStat__Match__6C190EBB");

            entity.HasOne(d => d.Team).WithMany(p => p.MatchStatistics)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__MatchStat__TeamI__6D0D32F4");
        });

        modelBuilder.Entity<Player>(entity =>
        {
            entity.HasKey(e => e.PlayerId).HasName("PK__Player__4A4E74C8F041A33E");

            entity.ToTable("Player");

            entity.HasIndex(e => e.Nationality, "IX_Player_Nationality");

            entity.HasIndex(e => e.TeamId, "IX_Player_TeamId");

            entity.HasIndex(e => e.ApiPlayerId, "UQ__Player__40FC95B4282280D7").IsUnique();

            entity.Property(e => e.BirthCountry)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.BirthPlace)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.HeightCm).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LastName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Nationality)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PhotoUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Position)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.WeightKg).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Team).WithMany(p => p.Players)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__Player__TeamId__4E88ABD4");
        });

        modelBuilder.Entity<PlayerMatchStatistic>(entity =>
        {
            entity.HasKey(e => e.PlayerMatchStatId).HasName("PK__PlayerMa__7941EF4EA9A6718B");

            entity.HasIndex(e => e.MatchId, "IX_PlayerMatchStatistics_MatchId");

            entity.Property(e => e.ExpectedGoals).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Rating).HasColumnType("decimal(3, 2)");

            entity.HasOne(d => d.Match).WithMany(p => p.PlayerMatchStatistics)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK__PlayerMat__Match__787EE5A0");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerMatchStatistics)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK__PlayerMat__Playe__797309D9");

            entity.HasOne(d => d.Team).WithMany(p => p.PlayerMatchStatistics)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__PlayerMat__TeamI__7A672E12");
        });

        modelBuilder.Entity<PlayerSeasonStatistic>(entity =>
        {
            entity.HasKey(e => e.PlayerStatisticsId).HasName("PK__PlayerSe__3A162D3E73339DF6");

            entity.HasIndex(e => e.PlayerId, "IX_PlayerSeasonStatistics_PlayerId");

            entity.Property(e => e.DribblesSuccessRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DuelsWonRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.PassesAccuracy).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Rating).HasColumnType("decimal(3, 2)");

            entity.HasOne(d => d.League).WithMany(p => p.PlayerSeasonStatistics)
                .HasForeignKey(d => d.LeagueId)
                .HasConstraintName("FK__PlayerSea__Leagu__68487DD7");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerSeasonStatistics)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK__PlayerSea__Playe__66603565");

            entity.HasOne(d => d.Season).WithMany(p => p.PlayerSeasonStatistics)
                .HasForeignKey(d => d.SeasonId)
                .HasConstraintName("FK__PlayerSea__Seaso__693CA210");

            entity.HasOne(d => d.Team).WithMany(p => p.PlayerSeasonStatistics)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__PlayerSea__TeamI__6754599E");
        });

        modelBuilder.Entity<Season>(entity =>
        {
            entity.HasKey(e => e.SeasonId).HasName("PK__Season__C1814E38E7292FDE");

            entity.ToTable("Season");

            entity.HasIndex(e => e.LeagueId, "IX_Season_LeagueId");

            entity.Property(e => e.ApiCoverage).IsUnicode(false);
            entity.Property(e => e.IsCurrentSeason).HasDefaultValue(false);

            entity.HasOne(d => d.League).WithMany(p => p.Seasons)
                .HasForeignKey(d => d.LeagueId)
                .HasConstraintName("FK__Season__LeagueId__3B75D760");
        });

        modelBuilder.Entity<Sidelined>(entity =>
        {
            entity.HasKey(e => e.SidelinedId).HasName("PK__Sideline__0960E42D5B902DD3");

            entity.ToTable("Sidelined");

            entity.Property(e => e.GamesMissed).HasDefaultValue(0);
            entity.Property(e => e.IsCompleted).HasDefaultValue(false);
            entity.Property(e => e.SidelinedType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Player).WithMany(p => p.Sidelineds)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK__Sidelined__Playe__03F0984C");

            entity.HasOne(d => d.Season).WithMany(p => p.Sidelineds)
                .HasForeignKey(d => d.SeasonId)
                .HasConstraintName("FK__Sidelined__Seaso__06CD04F7");

            entity.HasOne(d => d.Team).WithMany(p => p.Sidelineds)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__Sidelined__TeamI__05D8E0BE");
        });

        modelBuilder.Entity<Stadium>(entity =>
        {
            entity.HasKey(e => e.StadiumId).HasName("PK__Stadium__ED8330583FCB2B9F");

            entity.ToTable("Stadium");

            entity.HasIndex(e => e.ApiVenueId, "UQ__Stadium__6F33BECC88BA50DA").IsUnique();

            entity.Property(e => e.Address)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.City)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.IsNationalStadium).HasDefaultValue(false);
            entity.Property(e => e.StadiumName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Surface)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Standing>(entity =>
        {
            entity.HasKey(e => e.StandingId).HasName("PK__Standing__FC2758C14F0437DD");

            entity.HasIndex(e => new { e.LeagueId, e.SeasonId }, "IX_Standings_LeagueId_SeasonId");

            entity.Property(e => e.ApiLastUpdated).HasColumnType("datetime");
            entity.Property(e => e.AwayRecord).IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Form)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.HomeRecord).IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.League).WithMany(p => p.Standings)
                .HasForeignKey(d => d.LeagueId)
                .HasConstraintName("FK__Standings__Leagu__5CD6CB2B");

            entity.HasOne(d => d.Season).WithMany(p => p.Standings)
                .HasForeignKey(d => d.SeasonId)
                .HasConstraintName("FK__Standings__Seaso__5DCAEF64");

            entity.HasOne(d => d.Team).WithMany(p => p.Standings)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__Standings__TeamI__5EBF139D");
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.TeamId).HasName("PK__Team__123AE799D531591C");

            entity.ToTable("Team");

            entity.Property(e => e.LogoUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ShortName)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Club).WithMany(p => p.Teams)
                .HasForeignKey(d => d.ClubId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Team_Club");

            entity.HasOne(d => d.League).WithMany(p => p.Teams)
                .HasForeignKey(d => d.LeagueId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Team_League");

            entity.HasOne(d => d.Stadium).WithMany(p => p.Teams)
                .HasForeignKey(d => d.StadiumId)
                .HasConstraintName("FK_Team_Stadium");
        });

        modelBuilder.Entity<TeamStatistic>(entity =>
        {
            entity.HasKey(e => e.TeamStatId).HasName("PK__TeamStat__A0F24F8C98D4F1F2");

            entity.HasOne(d => d.League).WithMany(p => p.TeamStatistics)
                .HasForeignKey(d => d.LeagueId)
                .HasConstraintName("FK__TeamStati__Leagu__7E37BEF6");

            entity.HasOne(d => d.Season).WithMany(p => p.TeamStatistics)
                .HasForeignKey(d => d.SeasonId)
                .HasConstraintName("FK__TeamStati__Seaso__7F2BE32F");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamStatistics)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__TeamStati__TeamI__7D439ABD");
        });

        modelBuilder.Entity<Transfer>(entity =>
        {
            entity.HasKey(e => e.TransferId).HasName("PK__Transfer__9549009130B11A7E");

            entity.Property(e => e.TransferType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.FromTeam).WithMany(p => p.TransferFromTeams)
                .HasForeignKey(d => d.FromTeamId)
                .HasConstraintName("FK__Transfers__FromT__628FA481");

            entity.HasOne(d => d.Player).WithMany(p => p.Transfers)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK__Transfers__Playe__619B8048");

            entity.HasOne(d => d.ToTeam).WithMany(p => p.TransferToTeams)
                .HasForeignKey(d => d.ToTeamId)
                .HasConstraintName("FK__Transfers__ToTea__6383C8BA");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("User");

            entity.HasIndex(e => e.Username).IsUnique();
            entity.HasIndex(e => e.Email).IsUnique();

            entity.Property(e => e.Username).HasMaxLength(50).IsRequired();
            entity.Property(e => e.Email).HasMaxLength(255).IsRequired();
            entity.Property(e => e.PasswordHash).HasMaxLength(500).IsRequired();
            entity.Property(e => e.FullName).HasMaxLength(150).IsRequired();
            entity.Property(e => e.IsEmailVerified).HasDefaultValue(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.FailedLoginAttempts).HasDefaultValue(0);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("GETUTCDATE()");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId);

            entity.ToTable("Role");

            entity.HasIndex(e => e.RoleName).IsUnique();

            entity.Property(e => e.RoleName).HasMaxLength(50).IsRequired();
            entity.Property(e => e.Description).HasMaxLength(255);

            entity.HasData(
                new Role { RoleId = 1, RoleName = "User", Description = "Default user role" },
                new Role { RoleId = 2, RoleName = "Admin", Description = "Administrator role" }
            );
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId });

            entity.ToTable("UserRole");

            entity.Property(e => e.AssignedAt).HasDefaultValueSql("GETUTCDATE()");

            entity.HasOne(d => d.User)
                .WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(d => d.Role)
                .WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.ToTable("RefreshToken");

            entity.HasIndex(e => e.Token).IsUnique();

            entity.Property(e => e.Token).HasMaxLength(200).IsRequired();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");

            entity.HasOne(d => d.User)
                .WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<EmailVerificationToken>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.ToTable("EmailVerificationToken");

            entity.HasIndex(e => e.Token).IsUnique();

            entity.Property(e => e.Token).HasMaxLength(200).IsRequired();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.IsUsed).HasDefaultValue(false);

            entity.HasOne(d => d.User)
                .WithMany(p => p.EmailVerificationTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<PasswordResetToken>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.ToTable("PasswordResetToken");

            entity.HasIndex(e => e.Token).IsUnique();

            entity.Property(e => e.Token).HasMaxLength(200).IsRequired();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.IsUsed).HasDefaultValue(false);

            entity.HasOne(d => d.User)
                .WithMany(p => p.PasswordResetTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            foreach (var property in entityType.GetProperties())
            {
                if (property.ClrType == typeof(string))
                {
                    property.SetIsUnicode(true);
                }
            }
        }

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}