// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace VNFootballLeagues.Repositories.Models;

public partial class VNFootballLeaguesDBContext : DbContext
{
    public VNFootballLeaguesDBContext(DbContextOptions<VNFootballLeaguesDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Action> Actions { get; set; }

    public virtual DbSet<ActionsPlayerStatistic> ActionsPlayerStatistics { get; set; }

    public virtual DbSet<ActionsPosition> ActionsPositions { get; set; }

    public virtual DbSet<AnalyticalPost> AnalyticalPosts { get; set; }

    public virtual DbSet<Club> Clubs { get; set; }

    public virtual DbSet<Collaborator> Collaborators { get; set; }

    public virtual DbSet<Contract> Contracts { get; set; }

    public virtual DbSet<League> Leagues { get; set; }

    public virtual DbSet<Match> Matches { get; set; }

    public virtual DbSet<MatchResult> MatchResults { get; set; }

    public virtual DbSet<Player> Players { get; set; }

    public virtual DbSet<PlayerMatch> PlayerMatches { get; set; }

    public virtual DbSet<PlayerRating> PlayerRatings { get; set; }

    public virtual DbSet<PlayerStatistic> PlayerStatistics { get; set; }

    public virtual DbSet<Position> Positions { get; set; }

    public virtual DbSet<RatingPoint> RatingPoints { get; set; }

    public virtual DbSet<Season> Seasons { get; set; }

    public virtual DbSet<Stadium> Stadia { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Action>(entity =>
        {
            entity.HasKey(e => e.ActionId).HasName("PK__Actions__FFE3F4D9781AA31F");

            entity.Property(e => e.ActionName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ActionsPlayerStatistic>(entity =>
        {
            entity.HasKey(e => new { e.ActionId, e.PlayerStatisticsId }).HasName("PK__Actions___72A974619F82EBBC");

            entity.ToTable("Actions_PlayerStatistics");

            entity.HasOne(d => d.Action).WithMany(p => p.ActionsPlayerStatistics)
                .HasForeignKey(d => d.ActionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_APS_Action");

            entity.HasOne(d => d.PlayerStatistics).WithMany(p => p.ActionsPlayerStatistics)
                .HasForeignKey(d => d.PlayerStatisticsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_APS_Stats");
        });

        modelBuilder.Entity<ActionsPosition>(entity =>
        {
            entity.HasKey(e => new { e.ActionId, e.PositionId }).HasName("PK__Actions___79E84D7E4931E05F");

            entity.ToTable("Actions_Position");

            entity.HasOne(d => d.Action).WithMany(p => p.ActionsPositions)
                .HasForeignKey(d => d.ActionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AP_Action");

            entity.HasOne(d => d.Position).WithMany(p => p.ActionsPositions)
                .HasForeignKey(d => d.PositionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AP_Position");
        });

        modelBuilder.Entity<AnalyticalPost>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK__Analytic__AA1260189801262A");

            entity.ToTable("AnalyticalPost");

            entity.Property(e => e.Content)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Title)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Club>(entity =>
        {
            entity.HasKey(e => e.ClubId).HasName("PK__Club__D35058E7ED56ECB1");

            entity.ToTable("Club");

            entity.Property(e => e.City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ClubName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Owner)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Collaborator>(entity =>
        {
            entity.HasKey(e => e.CollaboratorId).HasName("PK__Collabor__3AC201E370EDA551");

            entity.Property(e => e.CollaboratorName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Organization)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Contract>(entity =>
        {
            entity.HasKey(e => e.ContractId).HasName("PK__Contract__C90D346989927418");

            entity.ToTable("Contract");

            entity.Property(e => e.ContractType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Club).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("FK_Contract_Club");

            entity.HasOne(d => d.Player).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contract_Player");

            entity.HasOne(d => d.Team).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contract_Team");
        });

        modelBuilder.Entity<League>(entity =>
        {
            entity.HasKey(e => e.LeagueId).HasName("PK__League__10ABBCF41BF5220C");

            entity.ToTable("League");

            entity.Property(e => e.LeagueName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Match>(entity =>
        {
            entity.HasKey(e => e.MatchId).HasName("PK__Match__4218C8170D620342");

            entity.ToTable("Match");

            entity.Property(e => e.RefereeName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.AwayTeam).WithMany(p => p.MatchAwayTeams)
                .HasForeignKey(d => d.AwayTeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_AwayTeam");

            entity.HasOne(d => d.HomeTeam).WithMany(p => p.MatchHomeTeams)
                .HasForeignKey(d => d.HomeTeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_HomeTeam");

            entity.HasOne(d => d.Season).WithMany(p => p.Matches)
                .HasForeignKey(d => d.SeasonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_Season");

            entity.HasOne(d => d.Stadium).WithMany(p => p.Matches)
                .HasForeignKey(d => d.StadiumId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_Stadium");
        });

        modelBuilder.Entity<MatchResult>(entity =>
        {
            entity.HasKey(e => e.ResultId).HasName("PK__Match_Re__976902082886A540");

            entity.ToTable("Match_Result");

            entity.Property(e => e.MatchStatus)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Match).WithMany(p => p.MatchResults)
                .HasForeignKey(d => d.MatchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Result_Match");

            entity.HasOne(d => d.WinnerTeam).WithMany(p => p.MatchResults)
                .HasForeignKey(d => d.WinnerTeamId)
                .HasConstraintName("FK_Result_Winner");
        });

        modelBuilder.Entity<Player>(entity =>
        {
            entity.HasKey(e => e.PlayerId).HasName("PK__Player__4A4E74C830B6D4EF");

            entity.ToTable("Player");

            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Nationality)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PreferredFoot)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Team).WithMany(p => p.Players)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK_Player_Team");

            entity.HasMany(d => d.Positions).WithMany(p => p.Players)
                .UsingEntity<Dictionary<string, object>>(
                    "PlayerPosition",
                    r => r.HasOne<Position>().WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PP_Position"),
                    l => l.HasOne<Player>().WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PP_Player"),
                    j =>
                    {
                        j.HasKey("PlayerId", "PositionId").HasName("PK__PlayerPo__CC45CD6F240970F8");
                        j.ToTable("PlayerPosition");
                    });
        });

        modelBuilder.Entity<PlayerMatch>(entity =>
        {
            entity.HasKey(e => new { e.PlayerId, e.MatchId }).HasName("PK__Player_M__2E6FF84964E449AC");

            entity.ToTable("Player_Match");

            entity.HasOne(d => d.Match).WithMany(p => p.PlayerMatches)
                .HasForeignKey(d => d.MatchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PM_Match");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerMatches)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PM_Player");

            entity.HasOne(d => d.PlayerStatistics).WithMany(p => p.PlayerMatches)
                .HasForeignKey(d => d.PlayerStatisticsId)
                .HasConstraintName("FK_PM_Stats");

            entity.HasOne(d => d.Position).WithMany(p => p.PlayerMatches)
                .HasForeignKey(d => d.PositionId)
                .HasConstraintName("FK_PM_Position");
        });

        modelBuilder.Entity<PlayerRating>(entity =>
        {
            entity.HasKey(e => e.RatingId).HasName("PK__PlayerRa__FCCDF87C3317AAA9");

            entity.ToTable("PlayerRating");

            entity.HasOne(d => d.PlayerStatistics).WithMany(p => p.PlayerRatings)
                .HasForeignKey(d => d.PlayerStatisticsId)
                .HasConstraintName("FK_PR_Stats");

            entity.HasOne(d => d.RatingPoint).WithMany(p => p.PlayerRatings)
                .HasForeignKey(d => d.RatingPointId)
                .HasConstraintName("FK_PR_Point");
        });

        modelBuilder.Entity<PlayerStatistic>(entity =>
        {
            entity.HasKey(e => e.PlayerStatisticsId).HasName("PK__PlayerSt__D4A80B8917AD1855");

            entity.HasOne(d => d.Collaborator).WithMany(p => p.PlayerStatistics)
                .HasForeignKey(d => d.CollaboratorId)
                .HasConstraintName("FK_PS_Collab");

            entity.HasOne(d => d.Match).WithMany(p => p.PlayerStatistics)
                .HasForeignKey(d => d.MatchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PS_Match");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerStatistics)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PS_Player");
        });

        modelBuilder.Entity<Position>(entity =>
        {
            entity.HasKey(e => e.PositionId).HasName("PK__Position__60BB9A7950ABAB36");

            entity.ToTable("Position");

            entity.Property(e => e.PositionCategory)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PositionCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PositionName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<RatingPoint>(entity =>
        {
            entity.HasKey(e => e.RatingPointId).HasName("PK__RatingPo__AFA4A7877FE00538");

            entity.HasOne(d => d.Action).WithMany(p => p.RatingPoints)
                .HasForeignKey(d => d.ActionId)
                .HasConstraintName("FK_RP_Action");
        });

        modelBuilder.Entity<Season>(entity =>
        {
            entity.HasKey(e => e.SeasonId).HasName("PK__Season__C1814E3895E7E8DD");

            entity.ToTable("Season");

            entity.HasOne(d => d.League).WithMany(p => p.Seasons)
                .HasForeignKey(d => d.LeagueId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Season_League");
        });

        modelBuilder.Entity<Stadium>(entity =>
        {
            entity.HasKey(e => e.StadiumId).HasName("PK__Stadium__ED8330582AA09DB9");

            entity.ToTable("Stadium");

            entity.Property(e => e.City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.StadiumName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.TeamId).HasName("PK__Team__123AE799D288EBB8");

            entity.ToTable("Team");

            entity.Property(e => e.CoachName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Club).WithMany(p => p.Teams)
                .HasForeignKey(d => d.ClubId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Team_Club");

            entity.HasMany(d => d.Seasons).WithMany(p => p.Teams)
                .UsingEntity<Dictionary<string, object>>(
                    "TeamSeason",
                    r => r.HasOne<Season>().WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TS_Season"),
                    l => l.HasOne<Team>().WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TS_Team"),
                    j =>
                    {
                        j.HasKey("TeamId", "SeasonId").HasName("PK__Team_Sea__8E22F37AF9DB580E");
                        j.ToTable("Team_Season");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}