// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class ActionsPosition
{
    public int ActionId { get; set; }

    public int PositionId { get; set; }

    public double? ImportanceWeight { get; set; }

    public virtual Action Action { get; set; }

    public virtual Position Position { get; set; }
}