// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Action
{
    public int ActionId { get; set; }

    public string ActionName { get; set; }

    public virtual ICollection<ActionsPlayerStatistic> ActionsPlayerStatistics { get; set; } = new List<ActionsPlayerStatistic>();

    public virtual ICollection<ActionsPosition> ActionsPositions { get; set; } = new List<ActionsPosition>();

    public virtual ICollection<RatingPoint> RatingPoints { get; set; } = new List<RatingPoint>();
}