// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class ActionsPlayerStatistic
{
    public int ActionId { get; set; }

    public int PlayerStatisticsId { get; set; }

    public int? Count { get; set; }

    public int? TotalWeightScore { get; set; }

    public virtual Action Action { get; set; }

    public virtual PlayerStatistic PlayerStatistics { get; set; }
}