// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class AnalyticsArticle
{
    public Guid ArticleId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public Guid AuthorId { get; set; }

    public DateTime PublishedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ArticleReference> ArticleReferences { get; set; } = new List<ArticleReference>();

    public virtual User Author { get; set; }
}