// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class AnalyticalPost
{
    public int PostId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateOnly? PostDate { get; set; }
}