// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class ArticleReference
{
    public Guid ReferenceId { get; set; }

    public Guid ArticleId { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? MatchId { get; set; }

    public Guid? CompetitionId { get; set; }

    public virtual AnalyticsArticle Article { get; set; }

    public virtual Competition Competition { get; set; }

    public virtual Match Match { get; set; }

    public virtual Player Player { get; set; }
}