// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class ChatSession
{
    public Guid SessionId { get; set; }

    public Guid UserId { get; set; }

    public string Title { get; set; }

    public DateTime StartTime { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual User User { get; set; }
}