// <auto-generated> This file was added for chat history. Maps to table [Message]. </auto-generated>
#nullable disable
using System;

namespace VNFootballLeagues.Repositories.Models;

public partial class ChatMessage
{
    public Guid MessageId { get; set; }

    public Guid SessionId { get; set; }

    public string Sender { get; set; }

    public string Text { get; set; }

    public DateTime Timestamp { get; set; }

    public virtual ChatSession Session { get; set; }
}
