// <auto-generated> This file was added for chat history. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class ChatSession
{
    public Guid SessionId { get; set; }

    public Guid UserId { get; set; }

    public string Title { get; set; }

    public DateTime StartTime { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<ChatMessage> Messages { get; set; } = new List<ChatMessage>();
}
