// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Club
{
    public int ClubId { get; set; }

    public string ClubName { get; set; }

    public int? FoundedYear { get; set; }

    public string City { get; set; }

    public string Owner { get; set; }

    public double? Budget { get; set; }

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();
}