// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Coach
{
    public int CoachId { get; set; }

    public int? ApiCoachId { get; set; }

    public string Name { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateOnly? BirthDate { get; set; }

    public string BirthPlace { get; set; }

    public string BirthCountry { get; set; }

    public int? Age { get; set; }

    public string Nationality { get; set; }

    public string PhotoUrl { get; set; }

    public int? TeamId { get; set; }

    public virtual ICollection<Sidelined> Sidelineds { get; set; } = new List<Sidelined>();

    public virtual Team Team { get; set; }
}