// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Competition
{
    public Guid CompetitionId { get; set; }

    public string CompetitionName { get; set; }

    public Guid SeasonId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ArticleReference> ArticleReferences { get; set; } = new List<ArticleReference>();

    public virtual ICollection<Match> Matches { get; set; } = new List<Match>();

    public virtual Season Season { get; set; }
}