// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Contract
{
    public int ContractId { get; set; }

    public int PlayerId { get; set; }

    public int TeamId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string ContractType { get; set; }

    public decimal? Salary { get; set; }

    public bool? IsActive { get; set; }

    public virtual Player Player { get; set; }

    public virtual Team Team { get; set; }
}