// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Contract
{
    public int ContractId { get; set; }

    public int PlayerId { get; set; }

    public int? FromTeamApiId { get; set; }
    public int? ToTeamApiId { get; set; }

    public string FromTeamName { get; set; }
    public string ToTeamName { get; set; }

    public DateTime? TransferDate { get; set; }

    public string TransferType { get; set; }

    public virtual Player Player { get; set; }
}