// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Lineup
{
    public int LineupId { get; set; }

    public int? MatchId { get; set; }

    public int? TeamId { get; set; }

    public string Formation { get; set; }

    public virtual Match Match { get; set; }

    public virtual Team Team { get; set; }
}