// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class MatchPlayer
{
    public Guid MatchPlayerId { get; set; }

    public Guid MatchId { get; set; }

    public Guid PlayerId { get; set; }

    public Guid TeamId { get; set; }

    public Guid PositionId { get; set; }

    public int? MinutesPlayed { get; set; }

    public string LineupStatus { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Match Match { get; set; }

    public virtual ICollection<MatchStatistic> MatchStatistics { get; set; } = new List<MatchStatistic>();

    public virtual Player Player { get; set; }

    public virtual ICollection<PlayerRating> PlayerRatings { get; set; } = new List<PlayerRating>();

    public virtual Position Position { get; set; }

    public virtual Team Team { get; set; }
}