// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class MatchStatistic
{
    public Guid StatisticId { get; set; }

    public Guid MatchPlayerId { get; set; }

    public int? PassesCompleted { get; set; }

    public int? Shots { get; set; }

    public int? ShotsOnTarget { get; set; }

    public int? Tackles { get; set; }

    public int? FoulsCommitted { get; set; }

    public int? Goals { get; set; }

    public int? Assists { get; set; }

    public bool IsDeleted { get; set; }

    public virtual MatchPlayer MatchPlayer { get; set; }
}