// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Match
{
    public Guid MatchId { get; set; }

    public DateTime MatchDatetime { get; set; }

    public string Venue { get; set; }

    public string MatchStatus { get; set; }

    public Guid HomeTeamId { get; set; }

    public Guid AwayTeamId { get; set; }

    public int? HomeScore { get; set; }

    public int? AwayScore { get; set; }

    public Guid SeasonId { get; set; }

    public Guid CompetitionId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ArticleReference> ArticleReferences { get; set; } = new List<ArticleReference>();

    public virtual Team AwayTeam { get; set; }

    public virtual Competition Competition { get; set; }

    public virtual Team HomeTeam { get; set; }

    public virtual ICollection<MatchPlayer> MatchPlayers { get; set; } = new List<MatchPlayer>();

    public virtual Season Season { get; set; }
}