// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class MatchStatistic
{
    public int StatId { get; set; }

    public int? MatchId { get; set; }

    public int? TeamId { get; set; }

    public int? Possession { get; set; }

    public int? Shots { get; set; }

    public int? ShotsOnTarget { get; set; }

    public int? Corners { get; set; }

    public int? Fouls { get; set; }

    public int? YellowCards { get; set; }

    public int? RedCards { get; set; }

    public int? Offsides { get; set; }

    public int? ShotsBlocked { get; set; }

    public int? ShotsInsideBox { get; set; }

    public int? ShotsOutsideBox { get; set; }

    public int? PassesAccuracy { get; set; }

    public int? PassesKey { get; set; }

    public int? DribblesAttempted { get; set; }

    public int? DribblesSuccess { get; set; }

    public int? DuelsWon { get; set; }

    public int? DuelsTotal { get; set; }

    public int? TacklesWon { get; set; }

    public int? Saves { get; set; }

    public int? Interceptions { get; set; }

    public int? Clearances { get; set; }

    public decimal? ExpectedGoals { get; set; }

    public virtual Match Match { get; set; }

    public virtual Team Team { get; set; }
}