// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Match
{
    public int MatchId { get; set; }

    public int SeasonId { get; set; }

    public int StadiumId { get; set; }

    public int HomeTeamId { get; set; }

    public int AwayTeamId { get; set; }

    public DateOnly? MatchDate { get; set; }

    public string RefereeName { get; set; }

    public virtual Team AwayTeam { get; set; }

    public virtual Team HomeTeam { get; set; }

    public virtual ICollection<MatchResult> MatchResults { get; set; } = new List<MatchResult>();

    public virtual ICollection<PlayerMatch> PlayerMatches { get; set; } = new List<PlayerMatch>();

    public virtual ICollection<PlayerStatistic> PlayerStatistics { get; set; } = new List<PlayerStatistic>();

    public virtual Season Season { get; set; }

    public virtual Stadium Stadium { get; set; }
}