// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class MatchEvent
{
    public int EventId { get; set; }

    public int? MatchId { get; set; }

    public int? TeamId { get; set; }

    public int? PlayerId { get; set; }

    public int? AssistPlayerId { get; set; }

    public string EventType { get; set; }

    public string Detail { get; set; }

    public int? EventTime { get; set; }

    public int? ExtraTime { get; set; }

    public string Period { get; set; }

    public string Comments { get; set; }

    public virtual Match Match { get; set; }

    public virtual Player Player { get; set; }

    public virtual Team Team { get; set; }
}