// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class MatchResult
{
    public int ResultId { get; set; }

    public int? WinnerTeamId { get; set; }

    public int? HomeScore { get; set; }

    public int? AwayScore { get; set; }

    public string MatchStatus { get; set; }

    public int? TotalTime { get; set; }

    public int MatchId { get; set; }

    public virtual Match Match { get; set; }

    public virtual Team WinnerTeam { get; set; }
}