// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Message
{
    public Guid MessageId { get; set; }

    public Guid SessionId { get; set; }

    public string Sender { get; set; }

    public string Text { get; set; }

    public DateTime Timestamp { get; set; }

    public virtual ChatSession Session { get; set; }
}