// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class PlayerRating
{
    public int RatingId { get; set; }

    public int? TotalActionScore { get; set; }

    public int? PlayerStatisticsId { get; set; }

    public int? RatingPointId { get; set; }

    public virtual PlayerStatistic PlayerStatistics { get; set; }

    public virtual RatingPoint RatingPoint { get; set; }
}