// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class PlayerMatch
{
    public int PlayerId { get; set; }

    public int MatchId { get; set; }

    public int? PositionId { get; set; }

    public int? PlayerStatisticsId { get; set; }

    public virtual Match Match { get; set; }

    public virtual Player Player { get; set; }

    public virtual PlayerStatistic PlayerStatistics { get; set; }

    public virtual Position Position { get; set; }
}