// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class PlayerRating
{
    public Guid RatingId { get; set; }

    public Guid MatchPlayerId { get; set; }

    public decimal RatingScore { get; set; }

    public DateTime CalculatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual MatchPlayer MatchPlayer { get; set; }

    public virtual ICollection<RatingExplanation> RatingExplanations { get; set; } = new List<RatingExplanation>();
}