// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Player
{
    public int PlayerId { get; set; }

    public int ApiPlayerId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string FullName { get; set; }

    public DateOnly? DateOfBirth { get; set; }
    public int? Age { get; set; }

    public string Nationality { get; set; }

    public string BirthPlace { get; set; }

    public string BirthCountry { get; set; }

    public decimal? HeightCm { get; set; }

    public decimal? WeightKg { get; set; }

    public string PhotoUrl { get; set; }

    public bool? IsInjured { get; set; }

    public int? TeamId { get; set; }
    public virtual Team Team { get; set; }

    public virtual ICollection<PlayerSeasonStatistic> PlayerSeasonStatistics { get; set; }
    public virtual ICollection<PlayerMatchStatistic> PlayerMatchStatistics { get; set; }
    public virtual ICollection<Contract> Contracts { get; set; }
}