// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class PlayerSeasonSummary
{
    public Guid SummaryId { get; set; }

    public Guid PlayerId { get; set; }

    public Guid SeasonId { get; set; }

    public int? MatchesPlayed { get; set; }

    public decimal? AverageRating { get; set; }

    public int? TotalGoals { get; set; }

    public int? TotalAssists { get; set; }

    public string FormTrend { get; set; }

    public DateTime LastUpdated { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Player Player { get; set; }

    public virtual Season Season { get; set; }
}