// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class PlayerStatistic
{
    public int PlayerStatisticsId { get; set; }

    public int MatchId { get; set; }

    public int? MinutesPlayed { get; set; }

    public int PlayerId { get; set; }

    public int? CollaboratorId { get; set; }

    public virtual ICollection<ActionsPlayerStatistic> ActionsPlayerStatistics { get; set; } = new List<ActionsPlayerStatistic>();

    public virtual Collaborator Collaborator { get; set; }

    public virtual Match Match { get; set; }

    public virtual Player Player { get; set; }

    public virtual ICollection<PlayerMatch> PlayerMatches { get; set; } = new List<PlayerMatch>();

    public virtual ICollection<PlayerRating> PlayerRatings { get; set; } = new List<PlayerRating>();
}