// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class PlayerSeason
{
    public Guid PlayerSeasonId { get; set; }

    public Guid PlayerId { get; set; }

    public Guid TeamId { get; set; }

    public Guid SeasonId { get; set; }

    public int? JerseyNumber { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Player Player { get; set; }

    public virtual Season Season { get; set; }

    public virtual Team Team { get; set; }
}