// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Position
{
    public Guid PositionId { get; set; }

    public string PositionCode { get; set; }

    public string PositionGroup { get; set; }

    public string Description { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<MatchPlayer> MatchPlayers { get; set; } = new List<MatchPlayer>();

    public virtual ICollection<Player> Players { get; set; } = new List<Player>();

    public virtual ICollection<PositionMetricWeight> PositionMetricWeights { get; set; } = new List<PositionMetricWeight>();
}