// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class PositionMetricWeight
{
    public Guid WeightId { get; set; }

    public Guid PositionId { get; set; }

    public string MetricName { get; set; }

    public decimal WeightValue { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Position Position { get; set; }
}