// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Position
{
    public int PositionId { get; set; }

    public string PositionName { get; set; }

    public string PositionCategory { get; set; }

    public string PositionCode { get; set; }

    public virtual ICollection<ActionsPosition> ActionsPositions { get; set; } = new List<ActionsPosition>();

    public virtual ICollection<PlayerMatch> PlayerMatches { get; set; } = new List<PlayerMatch>();

    public virtual ICollection<Player> Players { get; set; } = new List<Player>();
}