// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class RatingExplanation
{
    public Guid ExplanationId { get; set; }

    public Guid RatingId { get; set; }

    public string PositiveContributions { get; set; }

    public string NegativeContributions { get; set; }

    public string CalculationSummary { get; set; }

    public bool IsDeleted { get; set; }

    public virtual PlayerRating Rating { get; set; }
}