// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class RatingPoint
{
    public int RatingPointId { get; set; }

    public double? Point { get; set; }

    public int? ActionId { get; set; }

    public virtual Action Action { get; set; }

    public virtual ICollection<PlayerRating> PlayerRatings { get; set; } = new List<PlayerRating>();
}