// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Season
{
    public Guid SeasonId { get; set; }

    public string SeasonName { get; set; }

    public int Year { get; set; }

    public Guid LeagueId { get; set; }

    public bool IsCurrent { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Competition> Competitions { get; set; } = new List<Competition>();

    public virtual League League { get; set; }

    public virtual ICollection<Match> Matches { get; set; } = new List<Match>();

    public virtual ICollection<PlayerSeasonSummary> PlayerSeasonSummaries { get; set; } = new List<PlayerSeasonSummary>();

    public virtual ICollection<PlayerSeason> PlayerSeasons { get; set; } = new List<PlayerSeason>();
}