// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Sidelined
{
    public int SidelinedId { get; set; }

    public int? PlayerId { get; set; }

    public int? CoachId { get; set; }

    public int? TeamId { get; set; }

    public int? SeasonId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string SidelinedType { get; set; }

    public int? GamesMissed { get; set; }

    public bool? IsCompleted { get; set; }

    public virtual Coach Coach { get; set; }

    public virtual Player Player { get; set; }

    public virtual Season Season { get; set; }

    public virtual Team Team { get; set; }
}