// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Stadium
{
    public int StadiumId { get; set; }

    public int? ApiVenueId { get; set; }

    public string StadiumName { get; set; }

    public string City { get; set; }

    public int? Capacity { get; set; }

    public string Surface { get; set; }

    public string ImageUrl { get; set; }

    public string Address { get; set; }

    public bool? IsNationalStadium { get; set; }

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();
}