// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Stadium
{
    public int StadiumId { get; set; }

    public string StadiumName { get; set; }

    public string City { get; set; }

    public virtual ICollection<Match> Matches { get; set; } = new List<Match>();
}