// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Standing
{
    public int StandingId { get; set; }

    public int? LeagueId { get; set; }

    public int? SeasonId { get; set; }

    public int? TeamId { get; set; }

    public int? Rank { get; set; }

    public int? Played { get; set; }

    public int? Win { get; set; }

    public int? Draw { get; set; }

    public int? Loss { get; set; }

    public int? GoalsFor { get; set; }

    public int? GoalsAgainst { get; set; }

    public int? GoalDifference { get; set; }

    public int? Points { get; set; }

    public string Form { get; set; }

    public string Status { get; set; }

    public string Description { get; set; }

    public string HomeRecord { get; set; }

    public string AwayRecord { get; set; }

    public DateTime? ApiLastUpdated { get; set; }

    public virtual League League { get; set; }

    public virtual Season Season { get; set; }

    public virtual Team Team { get; set; }
}