// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class TeamStatistic
{
    public int TeamStatId { get; set; }

    public int? TeamId { get; set; }

    public int? LeagueId { get; set; }

    public int? SeasonId { get; set; }

    public int? Played { get; set; }

    public int? Wins { get; set; }

    public int? Draws { get; set; }

    public int? Losses { get; set; }

    public int? GoalsFor { get; set; }

    public int? GoalsAgainst { get; set; }

    public int? CleanSheets { get; set; }

    public int? FailedToScore { get; set; }

    public virtual League League { get; set; }

    public virtual Season Season { get; set; }

    public virtual Team Team { get; set; }
}