// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Team
{
    public int TeamId { get; set; }

    public string TeamName { get; set; }

    public string CoachName { get; set; }

    public int ClubId { get; set; }

    public virtual Club Club { get; set; }

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    public virtual ICollection<Match> MatchAwayTeams { get; set; } = new List<Match>();

    public virtual ICollection<Match> MatchHomeTeams { get; set; } = new List<Match>();

    public virtual ICollection<MatchResult> MatchResults { get; set; } = new List<MatchResult>();

    public virtual ICollection<Player> Players { get; set; } = new List<Player>();

    public virtual ICollection<Season> Seasons { get; set; } = new List<Season>();
}