// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Transfer
{
    public int TransferId { get; set; }

    public int? PlayerId { get; set; }

    public int ApiTransferId { get; set; }

    public string FromTeam { get; set; }

    public string ToTeam { get; set; }

    public string TransferFee { get; set; }
    public DateTime? TransferDate { get; set; }

    public string TransferType { get; set; }

    public virtual Player Player { get; set; }
}