// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VNFootballLeagues.Repositories.Models;

public partial class Transfer
{
    public int TransferId { get; set; }

    public int? PlayerId { get; set; }

    public int? FromTeamId { get; set; }

    public int? ToTeamId { get; set; }

    public DateTime? TransferDate { get; set; }

    public string TransferType { get; set; }

    public virtual Team FromTeam { get; set; }

    public virtual Player Player { get; set; }

    public virtual Team ToTeam { get; set; }
}